### ISSUE TITLE
Add link to speakerdeck

### ISSUE THREAD

**Issue by HEYGUL** [celinegilet/happy-town#1]
First of all, many many thanks for this awesome starter letting many people getting familiar with hexagonal clean architecture.

As I discovered it through your Devoxx France session, I think it could help to have direct link to your speaker deck, so people can follow steps to embrace hexagonal clean architecture.
(I am speaking of this https://speakerdeck.com/celinegilet/dune-architecture-n-tiers-a-une-architecture-clean-hexagonale)

Once again, thank you for this great job!

**Comment by celinegilet** [comment]
Great idea, it's done !
Thank you very much for this suggestion : the link has been added to the readme.md.
